### ISSUE TITLE
public type

### ISSUE THREAD

**Issue by skilesare** [canscale/StableBuffer#2]
Why isn't StableBuffer a public type?  I was trying to do

stable var nft_ledgers : RB.Tree<Text, SB.StableBuffer<Types.TransactionRecord>> = RB.init<Text, SB.StableBuffer<Types.TransactionRecord>>();

I had to add public in front of the type declaration.

**Comment by ByronBecker** [comment]
This was fixed in https://github.com/canscale/StableBuffer/commit/1af0e8814bac5ca7ed23a6c094204b46d9056c2e
